version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - app-network


  backend:
    build:
      context: ./backend
    container_name: express-backend
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - mongo

  frontend:
    build:
      context: ./client
    container_name: react-frontend
    ports:
      - "3000:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
